import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { contacts } from "../../rcnm-raw-data/contacts-clean";
import { events } from "../../rcnm-raw-data/events-clean";
import { ledger } from "../../rcnm-raw-data/ledger-clean";
import { repertoire } from "../../rcnm-raw-data/repertoire-clean";
import { venues } from "../../rcnm-raw-data/venues-clean";

// usage: npm run count-totals
// counts the full data set in rcnm-raw-data and writes only the numbers to data/rcnm-db-data-masked/totals.ts.
// the site reads that file, because rcnm-raw-data is not committed and never leaves this machine.

const destinationPath = resolve(
  import.meta.dirname,
  "../../data/rcnm-db-data-masked/totals.ts",
);

const firstSeasonYear = 2022;

type EventRecord = { season?: string; eventDate?: string; status?: string };
type LedgerRecord = { seasonId?: string; date?: string };

const allEvents = events as EventRecord[];
const allLedger = ledger as LedgerRecord[];

// entries with no event have no season, so place them by the year they were dated ("2023-..." -> "02")
function getSeason(entry: LedgerRecord): string | null {
  if (entry.seasonId) return entry.seasonId;
  if (!entry.date) return null;

  const year = Number(entry.date.slice(0, 4));
  return String(year - firstSeasonYear + 1).padStart(2, "0");
}

const datedEvents = allEvents.filter(
  (event) => event.season && event.eventDate,
);

const seasons = [...new Set(datedEvents.map((event) => event.season!))]
  .sort()
  .map((season) => {
    const seasonEvents = datedEvents.filter((event) => event.season === season);
    return {
      season,
      year: seasonEvents[0].eventDate!.slice(0, 4),
      events: seasonEvents.length,
      entries: allLedger.filter((entry) => getSeason(entry) === season).length,
    };
  });

// an event counts as scheduled once it has happened or has a date. the rest are ideas still being planned
const scheduledEvents = allEvents.filter(
  (event) => event.eventDate || event.status === "Finished",
);

const totals = {
  counts: {
    events: allEvents.length,
    contacts: contacts.length,
    repertoire: repertoire.length,
    venues: venues.length,
    ledger: allLedger.length,
  },
  eventCounts: {
    scheduled: scheduledEvents.length,
    planned: allEvents.length - scheduledEvents.length,
  },
  seasons,
};

writeFileSync(
  destinationPath,
  `// generated by scripts/rcnm/rcnm-count-totals.ts from the full data set. numbers only.\nexport const totals = ${JSON.stringify(totals, null, 2)};\n`,
);

console.log(`Wrote totals to ${destinationPath}`);
console.log(totals.counts, totals.eventCounts);
console.log(
  seasons
    .map((season) => `S${season.season} ${season.year}: ${season.entries}`)
    .join(" | "),
);
