// generated by scripts/rcnm/rcnm-count-totals.ts from the full data set. numbers only.
export const totals = {
  "counts": {
    "events": 72,
    "contacts": 370,
    "repertoire": 330,
    "venues": 29,
    "ledger": 1178
  },
  "eventCounts": {
    "scheduled": 34,
    "planned": 38
  },
  "seasons": [
    {
      "season": "00",
      "year": "2021",
      "events": 1,
      "entries": 20
    },
    {
      "season": "01",
      "year": "2022",
      "events": 7,
      "entries": 187
    },
    {
      "season": "02",
      "year": "2023",
      "events": 6,
      "entries": 202
    },
    {
      "season": "03",
      "year": "2024",
      "events": 6,
      "entries": 312
    },
    {
      "season": "04",
      "year": "2025",
      "events": 8,
      "entries": 339
    },
    {
      "season": "05",
      "year": "2026",
      "events": 6,
      "entries": 113
    }
  ]
};
